# Permalinks
permalink:        pretty

# Setup
title:            Dhruv's Blog
tagline:          Always Be Learnin'
url:              http://dhruvp.github.io
paginate:         1
baseurl:          /
author:
  name:           Dhruv Parthasarathy
  email:          dhruv@udacity.com
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
plugins:
  - jekyll-paginate
  - jekyll-katex

katex:
  js_path: "/Users/dhruv/.rvm/gems/ruby-2.5.3/gems/jekyll-katex-0.3.0/lib/assets/js"  # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor


  # Custom vars
version:          1.0.0
github:           https://github.com/dhruvp
